This will import our custom mounting file instead of enzyme
mb3online/jest-speck-plugin pull request #8
Opened 2016-11-30 17:22 UTC by pvienneau

2016-11-30 18:30 UTC, devriestyler approved these changes

2016-11-30 19:03 UTC, ericadamski requested changes

2016-11-30 19:03 UTC, ericadamski commented on src/index.js
> +function renderTemplate(template, params) {
this has trailing spaces

2016-12-01 02:07 UTC, ericadamski requested changes
Just a few small things :)

2016-12-01 02:07 UTC, ericadamski commented on dist/index.js
> +        fs.accessSync(path.resolve('lisdf'));
Pretty sure this isn't suppose to be 'lisdf'

2016-12-01 02:07 UTC, ericadamski commented on dist/index.js
> +        ; //do nothing
There is no need for the ';' do you like it style wise?

2016-12-01 02:07 UTC, ericadamski commented on dist/stubs/describe-shell-start.stub
> +import { render, shallow, mount } from '<%= relativeLibPath %>utils/enzyme/mounting.js';
Looking at this I think the ´/´ should be here.

2016-12-01 14:20 UTC, ericadamski approved these changes

2016-12-01 14:22 UTC, merged