This will update our test to use a custom jasmine matcher
mb3online/jest-speck-plugin pull request #9
Opened 2016-11-30 17:25 UTC by pvienneau

- Added `ReactTestUtils` since it seemed to be missing on execution of generated spec file
- Importing our `matchers.js` file for custom matchers
- Upated test code to use Object comparison

Must push https://github.com/mb3online/jest-speck-plugin/pull/8 before this PR, since I have merge that PR into this one for testing.

2016-11-30 18:30 UTC, devriestyler approved these changes

2016-11-30 19:02 UTC, ericadamski requested changes

2016-11-30 19:02 UTC, ericadamski commented on src/index.js
> +    for(let ii = 0; ii < folders.length; ii++){
What is this for?

2016-12-01 14:27 UTC, ericadamski approved these changes

2016-12-01 14:28 UTC, merged